### ISSUE TITLE
您的主题很喜欢， 有几个细节地方要请教下您

### ISSUE THREAD

**Issue by echohlne** [hugoface/ghost-theme-nanboone#1]
你的主题很大气很喜欢， 但是有几个细节需要请教下：
1. 请问下Tag或者分类页要怎么定义？之前没有用过Ghost
2. 请问页面下的超链接， 比如微博或者github在哪里更改地址，以及增删图标
期待您的回答

**Comment by luokailuo** [comment]
@echohlne 你好 
1：可以参考[这篇文章](https://yehuzi.com/gei-ghostbo-ke-tian-jia-tagsgui-dang-ye/)来自定义分类页
2：footer的超链接在 partials/footer.hbs 中可以修改，图标用的是fontawesome，具体使用方式你可以参考官网
