### ISSUE TITLE
文章页样式问题

### ISSUE THREAD

**Issue by a1262344305** [hugoface/ghost-theme-nanboone#3]
无意间搜到的这个主题，很喜欢。

但是有个问题，文章页的样式在微软 Edge 浏览器下有点问题，标题的背景图片变成黑块，试了下 IE 也是同样问题。

还有小问题，h1 h2 在手机上看会超出屏幕

**Comment by luokailuo** [comment]
@a1262344305 你好感谢反馈，请问你是用什么手机浏览的呢？另外，IE目前可能暂时没太多精力去适配了，望谅解～
